config/routes.rb
    get 'banco_check', :on => :collection
  end

  get '/bancos_inactivos', to: 'catbancos#inactivos', as: 'catbancos_inactivos'

  resources :cp

  get 'ventas/dashboard_ejecutivo_ventas', to: 'ventas#index', as: 'ventas1'
  get '/busqueda_clientes_captados', to: 'ventas#busqueda_clientes_captados', as: 'busqueda_clientes_captados'
  get '/busqueda_general_graficos', to: 'ventas#busqueda_general_graficos', as: 'busqueda_general_graficos'

  get 'ventas/dashboard_preventa', to: 'ventas#index2', as: 'ventas2'
  get '/busqueda_general_graficos_index2', to: 'ventas#busqueda_general_graficos_index2', as: 'busqueda_general_graficos_index2'
  get 'ventas/index3', as: 'ventas3'
  get 'ventas/index4', as: 'ventas4'

  resources :detallecob

  resources :stock do
    collection { post :import}#importar datos excel
  end

  resources :relactivos
  get '/activos_cliente/:id', to: 'relactivos#activos_cliente', as: 'activos_cliente'

  resources :activos do
     get 'activos_check_cb', :on => :collection
  end

  get '/activos_inactivos', to: 'activos#inactivos', as: 'activos_inactivos'

  resources :reldaycli
  get '/generar_ruta/:id/:id2', to: 'reldaycli#generar_ruta', as: 'generar_ruta'
  get '/busqueda_generacion_ruta', to: 'reldaycli#busqueda_generacion_ruta'

  get '/busqueda_vendedores_por_ruta', to: 'reldaycli#busqueda_vendedores_por_ruta'

  post '/reldaycli/datos', to: 'reldaycli#obtener_ruta_y_dia', as: 'ryd' #as es el nombre con el path que se le colocara
  get '/borrar_clientes_ruta_al_dia', to: 'reldaycli#borrar_clientes_ruta_al_dia', as: 'borrar_clientes_ruta_al_dia'

  get '/generar_ruta_agregar_de_forma_masiva', to: 'reldaycli#generar_ruta_agregar_de_forma_masiva', as: 'generar_ruta_agregar_de_forma_masiva'
  get '/generar_ruta_agregar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_agregar_seleccionar_todos_masivo', as: 'generar_ruta_agregar_seleccionar_todos_masivo'

  get '/generar_ruta_eliminar_de_forma_masiva', to: 'reldaycli#generar_ruta_eliminar_de_forma_masiva', as: 'generar_ruta_eliminar_de_forma_masiva'
  get '/generar_ruta_eliminar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_eliminar_seleccionar_todos_masivo', as: 'generar_ruta_eliminar_seleccionar_todos_masivo'

  get '/asig_clientes_entre_vendedores', to: 'reldaycli#asig_clientes_entre_vendedores', as: 'asig_clientes_entre_vendedores'
  get '/proc_transf_cli_vend', to: 'reldaycli#proc_transf_cli_vend', as: 'proc_transf_cli_vend'

  resources :secrutas
  resources :relproclas
  resources :clasproductos
  resources :relcliclas
  resources :detallelpromaster
  get '/detallepromocion/:id', to: 'detallelpromaster#index', as: 'detallelpromasterid'
  resources :listapromomaster
  resources :clasclientes
  resources :listapromo do
    resources :detallepromo
    get 'promociones_check', :on => :collection
  end
  get '/promociones_inactivas', to: 'listapromo#inactivos', as: 'listapromo_inactivos'

  resources :room_categories
  resources :hotels
  resources :relruclas
  resources :clasrutas
  resources :continuidad
  resources :configrutasp

  resources :rutas do
    collection { post :import}#importar datos excel
    get 'rutas_check', :on => :collection
  end
  get '/rutas_inactivas', to: 'rutas#inactivos', as: 'rutas_inactivos'
  get '/datos_ruta', to: 'rutas#datos_ruta', as: 'datos_ruta'

  resources :relclirutas
  get '/ruta/:id/clientes', to: 'relclirutas#ruta_clientes', as: 'ruta_clientes'
  get '/borrar_clientes_ruta', to: 'relclirutas#borrar_clientes_ruta', as: 'borrar_clientes_ruta'

  get '/relcliruta_agregar_de_forma_masiva', to: 'relclirutas#relcliruta_agregar_de_forma_masiva', as: 'relcliruta_agregar_de_forma_masiva'
  get '/relcliruta_agregar_seleccionar_todos_masivo', to: 'relclirutas#relcliruta_agregar_seleccionar_todos_masivo', as: 'relcliruta_agregar_seleccionar_todos_masivo'
  get '/relcliruta_eliminar_de_forma_masiva', to: 'relclirutas#relcliruta_eliminar_de_forma_masiva', as: 'relcliruta_eliminar_de_forma_masiva'
  get '/relcliruta_eliminar_seleccionar_todos_masivo', to: 'relclirutas#relcliruta_eliminar_seleccionar_todos_masivo', as: 'relcliruta_eliminar_seleccionar_todos_masivo'

  resources :perfiles
  resources :mvodev do
    get 'mvodev_check', :on => :collection

  end
  get '/mvodevoluciones_inactivos', to: 'mvodev#inactivos', as: 'mvodev_inactivos'

  resources :encuestas
  get '/encuestas_inactivas', to: 'encuestas#inactivos', as: 'encuestas_inactivos'

  resources :relmens

  resources :mensajes do
    get 'mensajes_check', :on => :collection
  end
  get 'mensajes/_inactivos', to: 'mensajes#inactivos', as: 'mensajes_inactivos'

  resources :cuotas
  get '/cuotas_inactivos', to: 'cuotas#inactivos', as: 'cuotas_inactivos'

  resources :td_comision
  resources :detallelp
  resources :detallelp
  resources :listap do
    collection { post :import}#importar datos excel
  end
  resources :relclilis
  resources :detalleld
  resources :th_comision do
    collection { post :import}#importar datos excel
  end
  get '/th_comision_inactivos', to: 'th_comision#inactivos', as: 'th_comision_inactivos'
  resources :listad do
    collection { post :import}#importar datos excel
  end

  resources :mvomerma do
    get 'mvomerma_check', :on => :collection
  end
  get '/mvomerma_inactivos', to: 'mvomerma#inactivos', as: 'mvomerma_inactivos'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :motivosnoventa do
    get 'motivosnoventa_check', :on => :collection

  end
  get '/motivosnoventa_inactivos', to: 'motivosnoventa#inactivos', as: 'motivosnoventa_inactivos'
  get '/busqueda_noventas', to: 'reportesventas#busqueda_noventas', as: 'busqueda_noventas'

  resources :formaspag do
    get 'formaspag_check', :on => :collection
  end
  get '/formaspago_inactivos', to: 'formaspag#inactivos', as: 'formaspag_inactivos'

  resources :productosxpzas

  resources :productoenvase
  get '/Productos/:id/envase', to: 'productoenvase#index', as: 'producto_envase'

  resources :detalleld

  get '/listald/:id/productos', to: 'detalleld#index', as: 'producto_detalle'
  get '/listald/:id/clientes', to: 'relclilis#index', as: 'cliente_detalle'

  get '/listap/:id/productos', to: 'detallelp#index', as: 'productos_listap'

  get '/lp_productos_agregar_de_forma_masiva', to: 'detallelp#lp_productos_agregar_de_forma_masiva', as: 'lp_productos_agregar_de_forma_masiva'
  get '/lp_productos_agregar_seleccionar_todos_masivo', to: 'detallelp#lp_productos_agregar_seleccionar_todos_masivo', as: 'lp_productos_agregar_seleccionar_todos_masivo'
  get '/lp_productos_eliminar_de_forma_masiva', to: 'detallelp#lp_productos_eliminar_de_forma_masiva', as: 'lp_productos_eliminar_de_forma_masiva'
  get '/lp_productos_eliminar_seleccionar_todos_masivo', to: 'detallelp#lp_productos_eliminar_seleccionar_todos_masivo', as: 'lp_productos_eliminar_seleccionar_todos_masivo'

  get '/listap/:id/clientes', to: 'relclilis#indexlistap', as: 'cliente_listap'

  get '/rcl_clientes_agregar_de_forma_masiva', to: 'relclilis#rcl_clientes_agregar_de_forma_masiva', as: 'rcl_clientes_agregar_de_forma_masiva'
  get '/rcl_clientes_agregar_seleccionar_todos_masivo', to: 'relclilis#rcl_clientes_agregar_seleccionar_todos_masivo', as: 'rcl_clientes_agregar_seleccionar_todos_masivo'
  get '/rcl_clientes_eliminar_de_forma_masiva', to: 'relclilis#rcl_clientes_eliminar_de_forma_masiva', as: 'rcl_clientes_eliminar_de_forma_masiva'
  get '/rcl_clientes_eliminar_seleccionar_todos_masivo', to: 'relclilis#rcl_clientes_eliminar_seleccionar_todos_masivo', as: 'rcl_clientes_eliminar_seleccionar_todos_masivo'

  get '/Promociones/:id/clientes', to: 'relclilis#clientes_promociones', as: 'clientes_promociones'

  get '/comision/:id/detalle', to: 'td_comision#index', as: 'comision_detalle'

  post "/usuario_nuevo", to: 'usuarios#create', as:'usuario_nuevo'

  get '/Mensajes/:id/productos', to: 'relmens#index', as: 'mensaje_productos'
  get '/Mensajes/:id/clientes', to: 'relmens#clientes', as: 'mensaje_clientes'
  get '/Mensajes/:id/rutas', to: 'relmens#rutas', as: 'mensaje_rutas'

  devise_for :usuarios, controllers: {
    registrations: "usuarios/registrations",
    sessions: "usuarios/sessions",
    passwords: "usuarios/passwords"}
    resources :usuarios do
      get 'usuarios_check', :on => :collection
      get 'usuarios_check2', :on => :collection

    end
    devise_scope :usuario do
      get 'usuarios/sessions/busqueda_sucursales', as: 'busqueda_sucursales'#Actualiza el selectbox de la sucursal dependindo de la empresa en el login
    end

    get '/usuarios_inactivos', to: 'usuarios#inactivos', as: 'usuarios_inactivos'
    get '/usuario_sucursales', to: 'usuarios#usuario_sucursales', as: 'usuario_sucursales'
    get '/busqueda_usuario_perfil', to: 'usuarios#busqueda_usuario_perfil', as: 'busqueda_usuario_perfil'

  resources :productos do
    collection { post :import}#importar datos excel
    get 'productos_check', :on => :collection
    get 'productos_codbarras_check', :on => :collection
  end
  get '/datos_producto', to: 'productos#datos_producto', as: 'datos_producto'
  post 'create_producto_generico', to: 'productos#create_producto_generico', as: 'create_producto_generico'

  get '/productos_inactivos', to: 'productos#inactivos', as: 'productos_inactivos'
  get '/busqueda_cp', to: 'clientes#busqueda_cp', as: 'busqueda_cp'

  resources :clientes do
    collection { post :import}#importar datos excel
    get 'clientes_check', :on => :collection
  end
  get '/impresion_clientes_pdf', to: 'clientes#impresion_clientes_pdf', as: 'impresion_clientes_pdf'

  get '/clientes_inactivos', to: 'clientes#inactivos', as: 'clientes_inactivos'
  get '/datos_cliente', to: 'clientes#datos_cliente', as: 'datos_cliente'

  resources :ayudantes do
    collection { post :import}#importar datos excel
  end

  resources :empresas do
    collection { post :import}#importar datos excel
  end
  get '/empresa/:id/sucursales', to: 'empresas#sucursales', as: 'sucursales'

app/controllers/relclirutas_controller.rb
class RelclirutasController < ApplicationController
  before_action :set_relcliruta, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /relclirutas
  # GET /relclirutas.json
  def ruta_clientes

    datos_relcliruta
    contadores
    @ruta = Ruta.datos_ruta(params[:id])

    respond_to do |format|
      format.html
      format.xls #para que se puedan enviar los datos de la busqueda del @search de la gema
      format.js #para que se puedan enviar los datos de la busqueda del @search de la gema
    end

  end

  def datos_relcliruta
    params[:IdEmpresa] = current_usuario.empresa_id

    @relcliruta = Relcliruta.new
    @relcliruta.build_reldayc
    @reldayc = Reldayc.new

    @searchc = Cliente.clientes_fuera_de_ruta(params).search(search_params)
    @searchc.sorts = 'id' if @searchc.sorts.empty?
    @clientes = @searchc.result().page(params[:clientes]).per(10)

    @search = Relcliruta.clientes_que_tiene(params[:id]).search(search_paramsx)
    @search.sorts = 'CodCliente' if @search.sorts.empty?
    @relclirutas = @search.result().page(params[:relclirutas]).per(10)
    @clientes_de_la_ruta_para_exportar = Relcliruta.clientes_que_tiene(params[:id])

  end

  def contadores
    params[:IdEmpresa] = current_usuario.empresa_id
    @searchc2 = Cliente.clientes_fuera_de_ruta2_contador(params).search(search_params)
    @cantidad_clientes_disponibles = @searchc2.result().count

    @search2 = Relcliruta.clientes_que_tiene(params[:id]).search(search_paramsx)
    @cantidad_clientes_relacionados_a_ruta = @search2.result().count
  end

  def borrar_clientes_ruta
    Relcliruta.where(:IdRuta => params[:IdRuta]).destroy_all

    params[:id] = params[:IdRuta]
    datos_relcliruta
    contadores
    respond_to do |format|
      format.js {flash.now[:notice] = 'Los clientes han sido eliminados.'} #ajax
    end

  end

  # GET /relclirutas/1
  # GET /relclirutas/1.json
  def show
  end

  # GET /relclirutas/new
  def new
    @relcliruta = Relcliruta.new
  end

  # GET /relclirutas/1/edit
  def edit
  end

  # POST /relclirutas
  # POST /relclirutas.json
  def create
    @relcliruta = Relcliruta.new(relcliruta_params)
    respond_to do |format|
      if @relcliruta.save
        params[:id] = @relcliruta.IdRuta
        contadores
        format.html { redirect_to @relcliruta, notice: 'Relcliruta was successfully created.' }
        format.json { render :show, status: :created, location: @relcliruta }
        format.js {flash.now[:notice] = 'El cliente se ha agregado de forma exitosa.'} #ajax
      else
        format.html { render :new }
        format.json { render json: @relcliruta.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al agregar el cliente.'} #ajax
      end
    end
  end

  # PATCH/PUT /relclirutas/1
  # PATCH/PUT /relclirutas/1.json
  def update
    respond_to do |format|
      if @relcliruta.update(relcliruta_params)
        format.html { redirect_to @relcliruta, notice: 'Relcliruta was successfully updated.' }
        format.json { render :show, status: :ok, location: @relcliruta }
      else
        format.html { render :edit }
        format.json { render json: @relcliruta.errors, status: :unprocessable_entity }
      end
    end
  end


  def relcliruta_agregar_seleccionar_todos_masivo
    params[:IdEmpresa] = current_usuario.empresa_id

    @searchc = Cliente.clientes_fuera_de_ruta(params).search(search_params)
    @todos_los_clientes_out_seleccionados = @searchc.result()


    respond_to do |format|
      format.js {flash.now[:notice] = 'Todos los clientes se han seleccionado de forma exitosa.'} #ajax
    end
  end

  def relcliruta_agregar_de_forma_masiva
    params[:lista_clientes_out].each do |(c,cliente_id)|
      Relcliruta.create(IdRuta: params[:id],IdCliente: cliente_id, IdEmpresa: current_usuario.empresa_id, Fecha: Time.now.strftime("%d-%m-%Y"))
    end

    datos_relcliruta
    contadores
    respond_to do |format|
        format.js {flash.now[:notice] = 'Todos los clientes se han agregado de forma exitosa.'} #ajax
    end
  end

  def relcliruta_eliminar_seleccionar_todos_masivo
    params[:search6] = current_usuario.empresa_id

    @search = Relcliruta.clientes_que_tiene(params[:id]).search(search_paramsx)
    @todos_los_clientes_in_seleccionados = @search.result()

    respond_to do |format|
      format.js {flash.now[:notice] = 'Todos los clientes se han seleccionado de forma exitosa.'} #ajax
    end
  end

  def relcliruta_eliminar_de_forma_masiva
    params[:lista_clientes_in].each do |(c,relcliruta_id)|
      @relcliruta = Relcliruta.find_by(Id: relcliruta_id)
      Reldayc.where(CodCli: @relcliruta.IdCliente, RutaId: params[:id]).delete_all #Eliminar su registro en el generador de rutas
      @relcliruta.destroy
    end

    datos_relcliruta
    contadores
    respond_to do |format|
        format.js {flash.now[:notice] = 'Todos los clientes seleccionados se han desvinculado de forma exitosa.'} #ajax
    end
  end



  # DELETE /relclirutas/1
  # DELETE /relclirutas/1.json
  def destroy
    @cliente = Cliente.find_by(IdCli: @relcliruta.IdCliente) #PARA RENDERIZAR EL CLIENTE
    Reldayc.where(CodCli: @relcliruta.IdCliente, RutaId: @relcliruta.IdRuta).delete_all #Eliminar su registro en el generador de rutas
    params[:id] = @relcliruta.IdRuta #<!--PARA QUE NO SE PIERDA EL ID DE LA LISTA CUANDO PASE POR EL EDITAR DEBIDO A QUE ESTARIA TOMANDO EL ID DEL REGISTRO Y NO EL DE LA LISTA-->
    @relcliruta.destroy
    @relcliruta.reldayc.destroy if @relcliruta.reldayc.present?

    respond_to do |format|
      contadores
      format.html { redirect_to relclirutas_url, notice: 'Relcliruta was successfully destroyed.' }
      format.json { head :no_content }
      format.js {flash.now[:notice] = 'El cliente se ha borrado de forma exitosa.'} #ajax
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relcliruta
      @relcliruta = Relcliruta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relcliruta_params
      params.require(:relcliruta).permit(:IdCliente, :IdRuta, :Fecha, :IdEmpresa, reldayc_attributes: [:RutaId, :CodCli, :IdEmpresa ])
    end
end

app/helpers/relclirutas_helper.rb
module RelclirutasHelper
end

app/views/relclirutas/_agregar_masivo.erb
<%= form_tag("/relcliruta_agregar_de_forma_masiva", method: 'get', remote: true, class: "form-horizontal" ) do %>
	<input type="hidden" id="id" value="<%=params[:id]%>" name="id" />

	<%= fields_for :lista_clientes_out do |ff|%>
	 <div id="campos_para_agregar_masivamente">

		<% if @todos_los_clientes_out_seleccionados.present?%>
			<% @todos_los_clientes_out_seleccionados.each do |cliente| %>
		    	<input type="hidden" id="global_<%=cliente.id%>" value="<%=cliente.id%>" name="lista_clientes_out[global_<%=cliente.id%>]" class="items_para_agregar" />

		    	  <script type="text/javascript">
							var myitem_agregar = document.getElementById('item_out_<%=cliente.id%>');
							if (myitem_agregar != null) document.getElementById("item_out_<%=cliente.id%>").checked = true;
				    </script>
		    <% end %>
	    <% end %>

	 </div>
	<% end %>

	<%= submit_tag "Agregar clientes seleccionados", name: "subaction", class: "btn btn-primary btn-xs", data: { disable_with: 'Agregando...' }, style:"float: right;" %>
<% end %>

<div id="boton_seleccionar_todos"><%=render 'boton_seleccionar_todos'%> </div>
<button class="btn warning" onclick="btn_borrar_seleccion_out()">Borrar selección</button>

<script>
function btn_borrar_seleccion_out() {
	$('.items_para_agregar').remove();
	$(".check_agregar").prop('checked', false);
}
</script>

app/views/relclirutas/_boton_seleccionar_todos_eliminar.erb
<%if params[:x].present?%>
	<%= link_to "Seleccionar todos", relcliruta_eliminar_seleccionar_todos_masivo_path(:id => params[:id], :x => {:cliente_IdCli_cont => params[:x][:cliente_IdCli_cont], :cliente_Nombre_cont => params[:x][:cliente_Nombre_cont], :cliente_Telefono_cont => params[:x][:cliente_Telefono_cont], :cliente_Colonia_cont => params[:x][:cliente_Colonia_cont]}, :commit=>"eliminar_masivo"), remote: true, class: "btn btn-primary btn-xs", data: { disable_with: 'Seleccionando...' }, style:"float: right;" %>
<%else%>
	<%= link_to "Seleccionar todos", relcliruta_eliminar_seleccionar_todos_masivo_path(:id => params[:id], :cliente_IdCli_cont => params[:cliente_IdCli_cont], :cliente_Nombre_cont => params[:cliente_Nombre_cont], :cliente_Telefono_cont => params[:cliente_Telefono_cont], :cliente_Colonia_cont => params[:cliente_Colonia_cont], :commit=>"eliminar_masivo"), remote: true, class: "btn btn-primary btn-xs", data: { disable_with: 'Seleccionando...' }, style:"float: right;" %>
<%end%>

app/views/relclirutas/_cantidad_clientes_out.html.erb
<h3>Total: <%=@cantidad_clientes_disponibles%></h3>

app/views/relclirutas/_clientesadded.html.erb
<%= search_form_for @search, as: :x, :remote=>"true", url: ruta_clientes_path(params[:id]), :method => :get do |f| %>
<div class="rwd">
  <table class="table table-striped table-bordered table-condensed table-hover rwd_auto">
        <thead>
          <tr>
            <th class="component_name_header_col"><%= sort_link @search, :cliente_IdCli, "Clave","relcliruta", {}, { :remote => true, :method => :get } %></th>
            <th class="component_name_header_col"><%= sort_link @search, :cliente_Nombre, "Nombre","relcliruta", {}, { :remote => true, :method => :get } %></th>
            <th class="component_name_header_col"><%= sort_link @search, :cliente_Telefono, "Teléfono","relcliruta", {}, { :remote => true, :method => :get } %></th>
            <th class="component_name_header_col"><%= sort_link @search, :cliente_Colonia, "Colonia","relcliruta", {}, { :remote => true, :method => :get } %></th>
            <th class="action_col"><%= t("basic.action") %></th>
          </tr>
          <tr>
            <th><%= f.text_field :cliente_IdCli_cont, class:"campo" %></th>
            <th><%= f.text_field :cliente_Nombre_cont, class:"campo" %></th>
            <th><%= f.text_field :cliente_Telefono_cont, class:"campo" %></th>
            <th><%= f.text_field :cliente_Colonia_cont, class:"campo" %></th>
            <th><%= f.submit "Buscar", data: {disable_with: 'Buscando...'} %></th>

          </tr>

        </thead>
        <tbody>
        </tbody>
      </table>
  </div><% end %>
<div class="rwd">
  <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
    </thead>
    <tbody>
      <table class="table table-striped table-bordered table-condensed table-hover">
        <%= search_form_for @search, as: :x, :remote=>"true", url: relcliruta_path(params[:id]), :method => :get do |f| %>
          <thead>
            <tr>
              <th></th>
              <th class="component_name_header_col"><%= sort_link @search, :cliente_IdCli, "Clave","relcliruta", {}, { :remote => true, :method => :get } %></th>
              <th class="component_name_header_col"><%= sort_link @search, :cliente_Nombre, "Nombre","relcliruta", {}, { :remote => true, :method => :get } %></th>
              <th class="component_name_header_col"><%= sort_link @search, :cliente_Telefono, "Teléfono","relcliruta", {}, { :remote => true, :method => :get } %></th>
              <th class="component_name_header_col"><%= sort_link @search, :cliente_Colonia, "Colonia","relcliruta", {}, { :remote => true, :method => :get } %></th>
            </tr>
          </thead>
        <% end %>
        <tbody id="container_relclirutas">
          <%= render partial: "/relclirutas/relcliruta", collection: @relclirutas %>
        </tbody>
      </table>
      <%= paginate @relclirutas, :param_name => 'relclirutas', params: {controller: 'relclirutas', action: 'ruta_clientes'}, :remote => true   %>
    </tbody>
  </table>
</div>

app/views/relclirutas/_form.html.erb
<%= form_for(@relcliruta) do |f| %>
  <% if @relcliruta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relcliruta.errors.count, "error") %> prohibited this relcliruta from being saved:</h2>

      <ul>
      <% @relcliruta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :IdCliente %><br>
    <%= f.text_field :IdCliente %>
  </div>
  <div class="field">
    <%= f.label :IdRuta %><br>
    <%= f.text_field :IdRuta %>
  </div>
  <div class="field">
    <%= f.label :IdEmpresa %><br>
    <%= f.text_field :IdEmpresa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relclirutas/destroy.js.erb
$("#relcliruta_<%= @relcliruta.id %>").fadeOut(500, function(){
  $(this).remove();
  $(".child").remove();
  $("#container_clientes").prepend('<%= j render(:partial => '/relclirutas/cliente', locals: { cliente: @cliente}) %>'); //Prepend before append

});
$("#cantidad_clientes_out").html("<%= escape_javascript(render("cantidad_clientes_out"))%>")
$("#cantidad_clientes_ruta").html("<%= escape_javascript(render("cantidad_clientes_ruta"))%>")

$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/relclirutas/new.html.erb
<h1>New Relcliruta</h1>

<%= render 'form' %>

<%= link_to 'Back', relclirutas_path %>

app/views/relclirutas/relcliruta_agregar_seleccionar_todos_masivo.js.erb
$("#agregar_masivo").html("<%= escape_javascript(render("agregar_masivo"))%>")
$("#boton_seleccionar_todos").html("<%= escape_javascript(render("boton_seleccionar_todos"))%>")
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/relclirutas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idcliente:</strong>
  <%= @relcliruta.IdCliente %>
</p>

<p>
  <strong>Idruta:</strong>
  <%= @relcliruta.IdRuta %>
</p>

<p>
  <strong>Idempresa:</strong>
  <%= @relcliruta.IdEmpresa %>
</p>

<%= link_to 'Edit', edit_relcliruta_path(@relcliruta) %> |
<%= link_to 'Back', relclirutas_path %>