config/routes.rb
Rails.application.routes.draw do

  resources :solicitudservicio
  get '/formulario_crear_servicio', to: 'solicitudservicio#formulario_crear_servicio', as: 'formulario_crear_servicio'

  resources :sabores do
    get 'sabor_check', :on => :collection
  end
  get '/sabores_inactivos', to: 'sabores#inactivos', as: 'sabores_inactivos'

  get 'verificar_credenciales_pos', to: 'pos#verificar_credenciales_pos', as: 'verificar_credenciales_pos'
  get 'pos/:Ruta/:PdaPW', to: 'pos#index', as: 'pos_index'
  get 'producto_para_POS', to: 'pos#producto_para_POS', as: 'producto_para_POS'
  get '/pos_vendedor_descuentoxproducto', to: 'pos#pos_vendedor_descuentoxproducto', as: 'pos_vendedor_descuentoxproducto'
  get '/procesar_venta', to: 'pos#procesar_venta', as: 'procesar_venta'
  delete '/pos_terminated/:id', to: 'pos#destroy', as: 'pos_terminated'

  get '/lista_rutas_disponibles', to: 'rutas#lista_rutas_disponibles', as: 'lista_rutas_disponibles'

  resources :password_resets

  resources :relprogrupos
  get '/grupo/:id/productos', to: 'relprogrupos#productos_grupo', as: 'productos_grupo'
  get 'comisiones', to: 'stored_procedures#comisiones', as: 'stored_procedures_comisiones'
  get 'vendedor_ruta_liquidacion', to: 'stored_procedures#vendedor_ruta_liquidacion', as: 'vendedor_ruta_liquidacion'
  get '/imprimir_comision', to: 'stored_procedures#pdf', as: 'comision_pdf'
  get 'pedidos_por_ruta', to: 'stored_procedures#cantidad_productosxpedido', as: 'cantidad_productosxpedido'
  get '/pedidos_ruta_impresion_etiquetas_pdf', to: 'stored_procedures#pedidos_ruta_impresion_etiquetas_pdf', as: 'pedidos_ruta_impresion_etiquetas_pdf'
  get 'consolidado_de_pedidos', to: 'stored_procedures#cantidad_productosxpedido_consolidado', as: 'cantidad_productosxpedido_consolidado'
  get '/productos_x_pedido_consolidado_pdf', to: 'stored_procedures#productos_x_pedido_consolidado_pdf', as: 'productos_x_pedido_consolidado_pdf'
  get 'monitoreo_de_precios', to: 'stored_procedures#monitoreo_de_precios', as: 'monitoreo_de_precios'
  get 'liquidaciones', to: 'stored_procedures#liquidaciones', as: 'liquidaciones'
  get 'reporte_consolidado_de_carga', to: 'stored_procedures#reporte_consolidado_de_carga', as: 'reporte_consolidado_de_carga'
  get 'reporte_consolidado_piezas', to: 'stored_procedures#reporte_consolidado_piezas', as: 'reporte_consolidado_piezas'
  get 'consentrado_pedido_del_dia_siguiente', to: 'stored_procedures#consentrado_pedido_del_dia_siguiente', as: 'consentrado_pedido_del_dia_siguiente'
  get 'reporte_consolidado_de_envases', to: 'stored_procedures#reporte_consolidado_de_envases', as: 'reporte_consolidado_de_envases'
  get '/reporte_liquidacion_concentrado', to: 'stored_procedures#reporte_liquidacion_concentrado', as: 'reporte_liquidacion_concentrado'
  post '/reporte_liquidacion_concentrado', to: 'stored_procedures#reporte_liquidacion_concentrado_detalles', as: 'reporte_liquidacion_concentrado_detalles'
  get '/reporte_liquidacion_concentrado_exportar', to: 'stored_procedures#reporte_liquidacion_concentrado_detalles', as: 'reporte_liquidacion_concentrado_exportar'

  resources :relvendrutas
  get '/ruta/:id/vendedores', to: 'relvendrutas#ruta_vendedores', as: 'ruta_vendedores'
  get '/borrar_vendedores_ruta', to: 'relvendrutas#borrar_vendedores_ruta', as: 'borrar_vendedores_ruta'

  get 'bitacoratiempos', to: 'bitacoratiempos#index', as: 'bitacoratiempos'

  resources :listacombo do
    get 'listcombo_check', :on => :collection
  end
  get '/combos_inactivos', to: 'listacombo#inactivos', as: 'listacombo_inactivos'
  get '/datos_listcombo', to: 'cuotasventa#datos_listcombo', as: 'datos_listcombo'
  resources :cuotasventa
  get '/datos_cuotaventa', to: 'cuotasventa#datos_cuotaventa', as: 'datos_cuotaventa'

  get 'inventario/inventario_inicial'
  get 'inventario/inventario_dia_siguiente'
  get 'inventario/inventario_sobrante'
  get 'inventario/inventario_total'

  resources :pedidos

  post '/pedidos/facturacion', to: 'pedidos#facturacion', as: 'facturacion_electronica'
  post '/pedidos/cancelar', to: 'pedidos#cancelar'

  get '/detalles_visor_de_pedidos', to: 'pedidos#detalles_visor_de_pedidos', as: 'detalles_pedidos'
  get '/visor_de_pedidos', to: 'pedidos#visor_de_pedidos', as: 'visor_de_pedidos'
  get '/imprimir_pedido_surtido', to: 'pedidos#pdf', as: 'pedidos_pdf'
  get '/consolidar', to: 'pedidos#consolidacion', as: 'consolidacion'
  get '/eliminar_pedido_consolidado', to: 'pedidos#eliminar_pedidos_consolidados', as: 'eliminar_pedido_consolidado'
  get '/surtir_de_forma_masiva', to: 'pedidos#surtir_de_forma_masiva', as: 'surtir_de_forma_masiva'
  get '/seleccionar_todos_surtimiento_masivo', to: 'pedidos#seleccionar_todos_surtimiento_masivo', as: 'seleccionar_todos_surtimiento_masivo'

  resources :backorder
  resources :pedidosliberados
  get '/busqueda_stored', to: 'pedidosliberados#busqueda_stored', as: 'busqueda_stored'

  resources :ctiket
  patch '/listap/:id/desincronizado', to: 'relclilis#desincronizado'
  put '/listap/:id/desincronizado', to: 'relclilis#desincronizado'

  resources :th_stockalmacen do
    collection { post :import}#importar datos excel
  end

  resources :cteimagen
  resources :incidencias do
    get 'incidencia_check', :on => :collection
  end
  get '/incidencias_inactivas', to: 'incidencias#inactivos', as: 'incidencias_inactivos'

  get 'mapa/index'

  resources :catmarcas do
    get 'catmarcas_check', :on => :collection
  end
  get '/marcas_inactivas', to: 'catmarcas#inactivos', as: 'catmarcas_inactivos'

  resources :catunidadmedida do
    get 'catunidadmed_check', :on => :collection
  end
  get '/medidas_inactivas', to: 'catunidadmedida#inactivos', as: 'catunidadmedida_inactivos'

  resources :catgrupos do
    get 'catgrupo_check', :on => :collection
  end
  get '/grupos_inactivos', to: 'catgrupos#inactivos', as: 'catgrupos_inactivos'

  resources :catbancos do
    get 'banco_check', :on => :collection
  end

  get '/bancos_inactivos', to: 'catbancos#inactivos', as: 'catbancos_inactivos'

  resources :cp

  get 'ventas/dashboard_ejecutivo_ventas', to: 'ventas#index', as: 'ventas1'
  get '/busqueda_clientes_captados', to: 'ventas#busqueda_clientes_captados', as: 'busqueda_clientes_captados'
  get '/busqueda_general_graficos', to: 'ventas#busqueda_general_graficos', as: 'busqueda_general_graficos'

  get 'ventas/dashboard_preventa', to: 'ventas#index2', as: 'ventas2'
  get '/busqueda_general_graficos_index2', to: 'ventas#busqueda_general_graficos_index2', as: 'busqueda_general_graficos_index2'
  get 'ventas/index3', as: 'ventas3'
  get 'ventas/index4', as: 'ventas4'

  resources :detallecob

  resources :stock do
    collection { post :import}#importar datos excel
  end

  resources :relactivos
  get '/activos_cliente/:id', to: 'relactivos#activos_cliente', as: 'activos_cliente'

  resources :activos do
     get 'activos_check_cb', :on => :collection
  end

  get '/activos_inactivos', to: 'activos#inactivos', as: 'activos_inactivos'

  resources :reldaycli
  get '/generar_ruta/:id/:id2', to: 'reldaycli#generar_ruta', as: 'generar_ruta'
  get '/busqueda_generacion_ruta', to: 'reldaycli#busqueda_generacion_ruta'

  get '/busqueda_vendedores_por_ruta', to: 'reldaycli#busqueda_vendedores_por_ruta'

  post '/reldaycli/datos', to: 'reldaycli#obtener_ruta_y_dia', as: 'ryd' #as es el nombre con el path que se le colocara
  get '/borrar_clientes_ruta_al_dia', to: 'reldaycli#borrar_clientes_ruta_al_dia', as: 'borrar_clientes_ruta_al_dia'

  get '/generar_ruta_agregar_de_forma_masiva', to: 'reldaycli#generar_ruta_agregar_de_forma_masiva', as: 'generar_ruta_agregar_de_forma_masiva'
  get '/generar_ruta_agregar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_agregar_seleccionar_todos_masivo', as: 'generar_ruta_agregar_seleccionar_todos_masivo'

  get '/generar_ruta_eliminar_de_forma_masiva', to: 'reldaycli#generar_ruta_eliminar_de_forma_masiva', as: 'generar_ruta_eliminar_de_forma_masiva'
  get '/generar_ruta_eliminar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_eliminar_seleccionar_todos_masivo', as: 'generar_ruta_eliminar_seleccionar_todos_masivo'

  get '/asig_clientes_entre_vendedores', to: 'reldaycli#asig_clientes_entre_vendedores', as: 'asig_clientes_entre_vendedores'
  get '/proc_transf_cli_vend', to: 'reldaycli#proc_transf_cli_vend', as: 'proc_transf_cli_vend'

  resources :secrutas
  resources :relproclas
  resources :clasproductos
  resources :relcliclas
  resources :detallelpromaster
  get '/detallepromocion/:id', to: 'detallelpromaster#index', as: 'detallelpromasterid'
  resources :listapromomaster
  resources :clasclientes
  resources :listapromo do
    resources :detallepromo
    get 'promociones_check', :on => :collection
  end
  get '/promociones_inactivas', to: 'listapromo#inactivos', as: 'listapromo_inactivos'

  resources :room_categories
  resources :hotels
  resources :relruclas
  resources :clasrutas
  resources :continuidad
  resources :configrutasp

  resources :rutas do
    collection { post :import}#importar datos excel
    get 'rutas_check', :on => :collection
  end
  get '/rutas_inactivas', to: 'rutas#inactivos', as: 'rutas_inactivos'
  get '/datos_ruta', to: 'rutas#datos_ruta', as: 'datos_ruta'

  resources :relclirutas
  get '/ruta/:id/clientes', to: 'relclirutas#ruta_clientes', as: 'ruta_clientes'
  get '/borrar_clientes_ruta', to: 'relclirutas#borrar_clientes_ruta', as: 'borrar_clientes_ruta'

  get '/relcliruta_agregar_de_forma_masiva', to: 'relclirutas#relcliruta_agregar_de_forma_masiva', as: 'relcliruta_agregar_de_forma_masiva'
  get '/relcliruta_agregar_seleccionar_todos_masivo', to: 'relclirutas#relcliruta_agregar_seleccionar_todos_masivo', as: 'relcliruta_agregar_seleccionar_todos_masivo'
  get '/relcliruta_eliminar_de_forma_masiva', to: 'relclirutas#relcliruta_eliminar_de_forma_masiva', as: 'relcliruta_eliminar_de_forma_masiva'

app/controllers/sabores_controller.rb
class SaboresController < ApplicationController
  before_action :set_sabor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!
  before_action :clear_search_index, :only => [:index]
  before_action :permiso_listar, only: [:index]
  before_action :permiso_create, only: [:create]
  before_action :permiso_update, only: [:update]
  before_action :permiso_destroy, only: [:destroy]

  def modulo
    @Descripcion_Modulo = "Catálogo de sabores"
  end

  # GET /sabores
  # GET /sabores.json
  def index
    @search = Sabor.activos.search(search_params)
    @search.sorts = 'Descripcion' if @search.sorts.empty?
    @sabores = @search.result().page(params[:page]).per(15)
    @sabor = Sabor.new
    @cantidad_sabores_activos = Sabor.activos.count

    respond_to do |format|
      format.html
      format.js 
      format.csv { send_data @sabores.to_csv}
      format.xls
    end
  end

  # GET /sabores
  # GET /sabores.json
  def inactivos
    @search = Sabor.inactivos.search(search_params)
    @search.sorts = 'Descripcion' if @search.sorts.empty?
    @sabores = @search.result().page(params[:page]).per(15)
    @sabor = Sabor.new
    @cantidad_sabores_inactivos = Sabor.inactivos.count

    respond_to do |format|
      format.html
      format.js 
      format.csv { send_data @sabores.to_csv}
      format.xls
    end
  end

  def sabor_check
    @saborx = Sabor.find_by_Clave(params[:sabor][:Clave])
    respond_to do |format|
    format.json { render :json => !@saborx }
    end
  end

  # GET /sabores/1
  # GET /sabores/1.json
  def show
  end

  # GET /sabores/new
  def new
    @sabor = Sabor.new
  end

  # GET /sabores/1/edit
  def edit
  end

  # POST /sabores
  # POST /sabores.json
  def create
    if @puede_crear != true
      return
    end
    @sabor = Sabor.new(sabor_params)

    respond_to do |format|
      if @sabor.save
        format.html { redirect_to @sabor, notice: 'Sabor was successfully created.' }
        format.json { render :show, status: :created, location: @sabor }
        format.js {flash.now[:notice] = 'El sabor se ha creado de forma exitosa.'} #ajax
      else
        format.html { render :new }
        format.json { render json: @sabor.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al crear el sabor.'} #ajax
      end
    end
  end

  # PATCH/PUT /sabores/1
  # PATCH/PUT /sabores/1.json
  def update
    if @puede_editar != true
      return
    end
    respond_to do |format|
      if @sabor.update(sabor_params)
        format.html { redirect_to @sabor, notice: 'Sabor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sabor }
        format.js {flash.now[:notice] = 'El sabor se ha actualizado de forma exitosa.'} #ajax
      else
        format.html { render :edit }
        format.json { render json: @sabor.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al actualizar el sabor.'} #ajax
      end
    end
  end

  # DELETE /sabores/1
  # DELETE /sabores/1.json
  def destroy
    if @puede_destroy != true
      return
    end
    respond_to do |format|
      format.html { redirect_to sabores_url, notice: 'Sabor was successfully destroyed.' }
      format.json { head :no_content }
      if @sabor.Status == true
        @sabor.update(Status:false)
        format.js {flash.now[:notice] = 'El sabor se ha borrado de forma exitosa.'} #ajax
      else
        @sabor.update(Status:true)
        format.js {flash.now[:notice] = 'El sabor se ha habilitado de forma exitosa.'} #ajax
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sabor
      @sabor = Sabor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sabor_params
      params.require(:sabor).permit(:Clave, :Descripcion, :Status)
    end
end

app/helpers/sabores_helper.rb
module SaboresHelper
end

app/views/sabores/_form.html.erb
<%= form_for(@sabor) do |f| %>
  <% if @sabor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sabor.errors.count, "error") %> prohibited this sabor from being saved:</h2>

      <ul>
      <% @sabor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Clave %><br>
    <%= f.text_field :Clave %>
  </div>
  <div class="field">
    <%= f.label :Descripcion %><br>
    <%= f.text_field :Descripcion %>
  </div>
  <div class="field">
    <%= f.label :Status %><br>
    <%= f.text_field :Status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sabores/_sabor.html.erb
<tr id="sabor_<%= sabor.id %>">
  <td class="col_left"><%= sabor.try(:Clave)%></td>
  <td class="col_left"><%= sabor.try(:Descripcion)%>
      <!--Modal - update producto-->
    <%= form_for(sabor, :method => :put, remote: true, html: {class: "form-horizontal formulario-validado-update#{sabor.id}"}) do |f| %><!--ajax-->
    <div nohidden class="modal fade si" id="myupdatesabor_<%= sabor.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Editar sabor</h4>
          </div>

          <div class="modal-body">

              <div class="form-group">
                <%= f.label :Descripcion, "Descripcion:", class: "control-label col-md-3"  %>
                <div class="col-md-9">
                  <%= f.text_field :Descripcion, class: "form-control ", required: "true"   %>
                </div>
              </div>

              <div class="form-group">
                <%= f.label :Status,"Activo:", class: "control-label col-xs-7 col-sm-6 col-md-2"%>
                <div class="col-md-1">
                  <%= f.check_box :Status,{checked: true} %>
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" id="myupdatebutton_<%= sabor.id %>" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <%= submit_tag "Actualizar", class: "btn btn-primary", data: { disable_with: 'Actualizando' }%>
          </div>
        </div>
      </div>
    </div>
    <%end%>
      <script>
        $(".formulario-validado-update<%=sabor.id%>").validate();

      </script>
  </td>

  <td>
    <div class="btn-group">
      <a class="btn dropdown-toggle btn-primary action-btn" href="#" data-toggle="dropdown">
       <%= t('basic.Acción') %>
      </a>
      <ul class="dropdown-menu posicion-menu">
        <li>
          <li>
            <button type="button" class="btn btn-default btn-lg btn-block" data-toggle="modal" data-target="#myupdatesabor_<%= sabor.id %>">
              Editar
            </button>
            <!--Destroy-->
            <% if sabor.Status == true%>
            <%= link_to 'Eliminar', sabor, method: :delete, class: "btn btn-default btn-xs", remote:true, data: {confirm: "¿Está seguro que desea eliminarlo?", disable_with: 'Eliminando...'}  %>
            <%else%>
              <%= link_to 'Habilitar', sabor, method: :delete, class: "btn btn-default btn-xs", remote:true, data: {confirm: "¿Está seguro que desea habilitarlo?", disable_with: 'Habilitando...'} %>
            <%end%>
          </li>
        </li>
      </ul>
    </div>
  </td>
</tr>

app/views/sabores/_sabores.html.erb
<%= search_form_for @search, :remote=>"true", url: sabores_path, :method => :get do |f| %>
<div class="rwd">
  <table class="table table-striped table-bordered table-condensed table-hover rwd_auto">
        <thead>
          <tr>
            <th class="col_left"><%= sort_link @search, :Clave, "Clave","sabor", {}, { :remote => true, :method => :get } %></th>
            <th class="col_left"><%= sort_link @search, :Descripcion, "Descripcion","sabor", {}, { :remote => true, :method => :get } %></th>
            <th class="action_col"><%= t("basic.action") %></th>
          </tr>
          <tr>
            <th><%= f.text_field :Clave_cont, class:"campo" %></th>
            <th><%= f.text_field :Descripcion_cont, class:"campo" %></th>
            <th><%= f.submit "Buscar", data: { disable_with: 'Buscando...' } %></th>
          </tr>

        </thead>
        <tbody>
        </tbody>
      </table>
  </div><% end %>




      <div class="rwd">
          <table class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <%= search_form_for @search, :remote=>"true", url: sabores_path, :method => :get do |f| %>
              <tr>
                <th class="col_left"><%= sort_link @search, :Clave, "Clave","sabor", {}, { :remote => true, :method => :get } %></th>
                <th class="col_left"><%= sort_link @search, :Descripcion, "Descripcion","sabor", {}, { :remote => true, :method => :get } %></th>
                <th class="action_col"><%= t("basic.action") %></th>
              </tr><% end %>
            </thead>
            <tbody id="container_sabores">
              <%= render @sabores %><!--carga todos los activos-->

            </tbody>
          </table>
          <%= paginate @sabores %>

  </div>

app/views/sabores/create.js.erb
<% if @puede_crear == true%>
  $("#mynewsabor").modal('hide');
  $(".sabor_clave").val('');
  $(".sabor_descripcion").val('');

  $("#container_sabores").prepend('<%= j render @sabor %>'); //Prepend before append
  $("#sabor_<%= @sabor.id %>").hide().fadeIn(1000);
<%end%>
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/sabores/destroy.js.erb
<% if @puede_destroy == true%>
  $("#sabor_<%= @sabor.id %>").fadeOut(500, function(){
    $(this).remove();
    $(".child").remove();
  });
<%end%>
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/sabores/edit.html.erb
<h1>Editing Sabor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sabor %> |
<%= link_to 'Back', sabores_path %>

app/views/sabores/inactivos.html.erb
<!--<p id="notice"><%= notice %></p>-->
<h1>Sabores inactivos</h1>
<h3>Total: <%=@cantidad_sabores_inactivos%></h3>
<style>
.container {
  width: 100%;
}

</style>


  <br>
  <br>

<div id="sabores"><%= render 'sabores' %></div>
<%= link_to 'Volver a Sabores', sabores_path, class: "btn btn-primary btn-lg" %>

app/views/sabores/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<h1>Sabores</h1>
<h3>Total: <%=@cantidad_sabores_activos%></h3>
<style>
.container {
  width: 100%;
}

</style>
  <div class="row">
    <div class="text-center">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mynewsabor">
        Nuevo Sabor
      </button>

    </div>
  </div>

  <br>
  <br>

<div id="sabores"><%= render 'sabores' %></div>



<!-- Modal create action -->
<%= form_for(@sabor, remote: true, html: {class: "form-horizontal sabor-validado"}) do |f| %> <!--ajax remote: true-->
  <div class="modal fade" id="mynewsabor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Agregar sabor</h4>
        </div>
        <div class="modal-body">

          <div class="form-group">
            <%= f.label :Clave, "Clave:", class: "control-label col-md-3"  %>
            <div class="col-md-7">
              <%= f.text_field :Clave, class: "form-control sabor_clave clave_sin_espacios_y_sin_caracteres_especiales",autofocus: true, required: "true"   %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :Descripcion, "Descripción:", class: "control-label col-md-3"  %>
            <div class="col-md-9">
              <%= f.text_field :Descripcion, class: "form-control sabor_descripcion", required: "true"   %>
            </div>
          </div>



          <div class="form-group">
            <%= f.label :Status,"Activo:", class: "control-label col-xs-7 col-sm-6 col-md-2"%>
            <div class="col-md-1">
              <%= f.check_box :Status,{checked: true} %>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewsabor">Cerrar</button>
          <%= f.submit "Crear", class: "btn btn-primary", data: { disable_with: 'Creando' }%>
        </div>
      </div>
    </div>
  </div>
<%end%>
<%= link_to 'Sabores eliminados ó inhabilitados<i class="fa fa-times-circle" aria-hidden="true"></i>'.html_safe, sabores_inactivos_path, class: "btn btn-danger btn-xs"%>

app/views/sabores/index.js.erb
$('#sabores').html('<%= escape_javascript(render("sabores")) %>');

app/views/sabores/new.html.erb
<h1>New Sabor</h1>

<%= render 'form' %>

<%= link_to 'Back', sabores_path %>

app/views/sabores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clave:</strong>
  <%= @sabor.Clave %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @sabor.Descripcion %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sabor.Status %>
</p>

<%= link_to 'Edit', edit_sabor_path(@sabor) %> |
<%= link_to 'Back', sabores_path %>

app/views/sabores/update.js.erb
<% if @puede_editar == true %>
  $("#myupdatesabor_<%= @sabor.id %>").modal('hide');

  $("#sabor_<%= @sabor.id %>").fadeOut(500, function(){
    $(this).remove();
    $(".child").remove();
    $("#container_sabores").prepend('<%= j render @sabor %>');
  });
<%end%>
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);