config/routes.rb
  get '/productos_x_pedido_consolidado_pdf', to: 'stored_procedures#productos_x_pedido_consolidado_pdf', as: 'productos_x_pedido_consolidado_pdf'
  get 'monitoreo_de_precios', to: 'stored_procedures#monitoreo_de_precios', as: 'monitoreo_de_precios'
  get 'liquidaciones', to: 'stored_procedures#liquidaciones', as: 'liquidaciones'
  get 'reporte_consolidado_de_carga', to: 'stored_procedures#reporte_consolidado_de_carga', as: 'reporte_consolidado_de_carga'
  get 'reporte_consolidado_piezas', to: 'stored_procedures#reporte_consolidado_piezas', as: 'reporte_consolidado_piezas'
  get 'consentrado_pedido_del_dia_siguiente', to: 'stored_procedures#consentrado_pedido_del_dia_siguiente', as: 'consentrado_pedido_del_dia_siguiente'
  get 'reporte_consolidado_de_envases', to: 'stored_procedures#reporte_consolidado_de_envases', as: 'reporte_consolidado_de_envases'
  get '/reporte_liquidacion_concentrado', to: 'stored_procedures#reporte_liquidacion_concentrado', as: 'reporte_liquidacion_concentrado'
  post '/reporte_liquidacion_concentrado', to: 'stored_procedures#reporte_liquidacion_concentrado_detalles', as: 'reporte_liquidacion_concentrado_detalles'
  get '/reporte_liquidacion_concentrado_exportar', to: 'stored_procedures#reporte_liquidacion_concentrado_detalles', as: 'reporte_liquidacion_concentrado_exportar'

  resources :relvendrutas
  get '/ruta/:id/vendedores', to: 'relvendrutas#ruta_vendedores', as: 'ruta_vendedores'
  get '/borrar_vendedores_ruta', to: 'relvendrutas#borrar_vendedores_ruta', as: 'borrar_vendedores_ruta'

  get 'bitacoratiempos', to: 'bitacoratiempos#index', as: 'bitacoratiempos'

  resources :listacombo do
    get 'listcombo_check', :on => :collection
  end
  get '/combos_inactivos', to: 'listacombo#inactivos', as: 'listacombo_inactivos'
  get '/datos_listcombo', to: 'cuotasventa#datos_listcombo', as: 'datos_listcombo'
  resources :cuotasventa
  get '/datos_cuotaventa', to: 'cuotasventa#datos_cuotaventa', as: 'datos_cuotaventa'

  get 'inventario/inventario_inicial'
  get 'inventario/inventario_dia_siguiente'
  get 'inventario/inventario_sobrante'
  get 'inventario/inventario_total'

  resources :pedidos

  post '/pedidos/facturacion', to: 'pedidos#facturacion', as: 'facturacion_electronica'
  post '/pedidos/cancelar', to: 'pedidos#cancelar'

  get '/detalles_visor_de_pedidos', to: 'pedidos#detalles_visor_de_pedidos', as: 'detalles_pedidos'
  get '/visor_de_pedidos', to: 'pedidos#visor_de_pedidos', as: 'visor_de_pedidos'
  get '/imprimir_pedido_surtido', to: 'pedidos#pdf', as: 'pedidos_pdf'
  get '/consolidar', to: 'pedidos#consolidacion', as: 'consolidacion'
  get '/eliminar_pedido_consolidado', to: 'pedidos#eliminar_pedidos_consolidados', as: 'eliminar_pedido_consolidado'
  get '/surtir_de_forma_masiva', to: 'pedidos#surtir_de_forma_masiva', as: 'surtir_de_forma_masiva'
  get '/seleccionar_todos_surtimiento_masivo', to: 'pedidos#seleccionar_todos_surtimiento_masivo', as: 'seleccionar_todos_surtimiento_masivo'

  resources :backorder
  resources :pedidosliberados
  get '/busqueda_stored', to: 'pedidosliberados#busqueda_stored', as: 'busqueda_stored'

  resources :ctiket
  patch '/listap/:id/desincronizado', to: 'relclilis#desincronizado'
  put '/listap/:id/desincronizado', to: 'relclilis#desincronizado'

  resources :th_stockalmacen do
    collection { post :import}#importar datos excel
  end

  resources :cteimagen
  resources :incidencias do
    get 'incidencia_check', :on => :collection
  end
  get '/incidencias_inactivas', to: 'incidencias#inactivos', as: 'incidencias_inactivos'

  get 'mapa/index'

  resources :catmarcas do
    get 'catmarcas_check', :on => :collection
  end
  get '/marcas_inactivas', to: 'catmarcas#inactivos', as: 'catmarcas_inactivos'

  resources :catunidadmedida do
    get 'catunidadmed_check', :on => :collection
  end
  get '/medidas_inactivas', to: 'catunidadmedida#inactivos', as: 'catunidadmedida_inactivos'

  resources :catgrupos do
    get 'catgrupo_check', :on => :collection
  end
  get '/grupos_inactivos', to: 'catgrupos#inactivos', as: 'catgrupos_inactivos'

  resources :catbancos do
    get 'banco_check', :on => :collection
  end

  get '/bancos_inactivos', to: 'catbancos#inactivos', as: 'catbancos_inactivos'

  resources :cp

  get 'ventas/dashboard_ejecutivo_ventas', to: 'ventas#index', as: 'ventas1'
  get '/busqueda_clientes_captados', to: 'ventas#busqueda_clientes_captados', as: 'busqueda_clientes_captados'
  get '/busqueda_general_graficos', to: 'ventas#busqueda_general_graficos', as: 'busqueda_general_graficos'

  get 'ventas/dashboard_preventa', to: 'ventas#index2', as: 'ventas2'
  get '/busqueda_general_graficos_index2', to: 'ventas#busqueda_general_graficos_index2', as: 'busqueda_general_graficos_index2'
  get 'ventas/index3', as: 'ventas3'
  get 'ventas/index4', as: 'ventas4'

  resources :detallecob

  resources :stock do
    collection { post :import}#importar datos excel
  end

  resources :relactivos
  get '/activos_cliente/:id', to: 'relactivos#activos_cliente', as: 'activos_cliente'

  resources :activos do
     get 'activos_check_cb', :on => :collection
  end

  get '/activos_inactivos', to: 'activos#inactivos', as: 'activos_inactivos'

  resources :reldaycli
  get '/generar_ruta/:id/:id2', to: 'reldaycli#generar_ruta', as: 'generar_ruta'
  get '/busqueda_generacion_ruta', to: 'reldaycli#busqueda_generacion_ruta'

  get '/busqueda_vendedores_por_ruta', to: 'reldaycli#busqueda_vendedores_por_ruta'

  post '/reldaycli/datos', to: 'reldaycli#obtener_ruta_y_dia', as: 'ryd' #as es el nombre con el path que se le colocara
  get '/borrar_clientes_ruta_al_dia', to: 'reldaycli#borrar_clientes_ruta_al_dia', as: 'borrar_clientes_ruta_al_dia'

  get '/generar_ruta_agregar_de_forma_masiva', to: 'reldaycli#generar_ruta_agregar_de_forma_masiva', as: 'generar_ruta_agregar_de_forma_masiva'
  get '/generar_ruta_agregar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_agregar_seleccionar_todos_masivo', as: 'generar_ruta_agregar_seleccionar_todos_masivo'

  get '/generar_ruta_eliminar_de_forma_masiva', to: 'reldaycli#generar_ruta_eliminar_de_forma_masiva', as: 'generar_ruta_eliminar_de_forma_masiva'
  get '/generar_ruta_eliminar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_eliminar_seleccionar_todos_masivo', as: 'generar_ruta_eliminar_seleccionar_todos_masivo'

  get '/asig_clientes_entre_vendedores', to: 'reldaycli#asig_clientes_entre_vendedores', as: 'asig_clientes_entre_vendedores'
  get '/proc_transf_cli_vend', to: 'reldaycli#proc_transf_cli_vend', as: 'proc_transf_cli_vend'

  resources :secrutas
  resources :relproclas
  resources :clasproductos
  resources :relcliclas
  resources :detallelpromaster
  get '/detallepromocion/:id', to: 'detallelpromaster#index', as: 'detallelpromasterid'
  resources :listapromomaster
  resources :clasclientes
  resources :listapromo do
    resources :detallepromo
    get 'promociones_check', :on => :collection
  end
  get '/promociones_inactivas', to: 'listapromo#inactivos', as: 'listapromo_inactivos'

  resources :room_categories
  resources :hotels
  resources :relruclas
  resources :clasrutas
  resources :continuidad
  resources :configrutasp

  resources :rutas do
    collection { post :import}#importar datos excel
    get 'rutas_check', :on => :collection
  end
  get '/rutas_inactivas', to: 'rutas#inactivos', as: 'rutas_inactivos'
  get '/datos_ruta', to: 'rutas#datos_ruta', as: 'datos_ruta'

  resources :relclirutas
  get '/ruta/:id/clientes', to: 'relclirutas#ruta_clientes', as: 'ruta_clientes'
  get '/borrar_clientes_ruta', to: 'relclirutas#borrar_clientes_ruta', as: 'borrar_clientes_ruta'

  get '/relcliruta_agregar_de_forma_masiva', to: 'relclirutas#relcliruta_agregar_de_forma_masiva', as: 'relcliruta_agregar_de_forma_masiva'
  get '/relcliruta_agregar_seleccionar_todos_masivo', to: 'relclirutas#relcliruta_agregar_seleccionar_todos_masivo', as: 'relcliruta_agregar_seleccionar_todos_masivo'
  get '/relcliruta_eliminar_de_forma_masiva', to: 'relclirutas#relcliruta_eliminar_de_forma_masiva', as: 'relcliruta_eliminar_de_forma_masiva'
  get '/relcliruta_eliminar_seleccionar_todos_masivo', to: 'relclirutas#relcliruta_eliminar_seleccionar_todos_masivo', as: 'relcliruta_eliminar_seleccionar_todos_masivo'

  resources :perfiles
  resources :mvodev do
    get 'mvodev_check', :on => :collection

  end
  get '/mvodevoluciones_inactivos', to: 'mvodev#inactivos', as: 'mvodev_inactivos'

  resources :encuestas
  get '/encuestas_inactivas', to: 'encuestas#inactivos', as: 'encuestas_inactivos'

  resources :relmens

  resources :mensajes do
    get 'mensajes_check', :on => :collection
  end
  get 'mensajes/_inactivos', to: 'mensajes#inactivos', as: 'mensajes_inactivos'

  resources :cuotas
  get '/cuotas_inactivos', to: 'cuotas#inactivos', as: 'cuotas_inactivos'

  resources :td_comision
  resources :detallelp
  resources :detallelp
  resources :listap do
    collection { post :import}#importar datos excel
  end
  resources :relclilis
  resources :detalleld
  resources :th_comision do
    collection { post :import}#importar datos excel
  end
  get '/th_comision_inactivos', to: 'th_comision#inactivos', as: 'th_comision_inactivos'
  resources :listad do
    collection { post :import}#importar datos excel
  end

  resources :mvomerma do
    get 'mvomerma_check', :on => :collection
  end
  get '/mvomerma_inactivos', to: 'mvomerma#inactivos', as: 'mvomerma_inactivos'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :motivosnoventa do
    get 'motivosnoventa_check', :on => :collection

  end
  get '/motivosnoventa_inactivos', to: 'motivosnoventa#inactivos', as: 'motivosnoventa_inactivos'
  get '/busqueda_noventas', to: 'reportesventas#busqueda_noventas', as: 'busqueda_noventas'

  resources :formaspag do
    get 'formaspag_check', :on => :collection
  end
  get '/formaspago_inactivos', to: 'formaspag#inactivos', as: 'formaspag_inactivos'

  resources :productosxpzas

  resources :productoenvase

app/models/incidencia.rb
class Incidencia < ActiveRecord::Base
  self.primary_key = "Clave"
  self.table_name = 'Incidencias' #para la gema ransack pueda encontrar la tabla(esto parece que solo pasa en sqlserver)
  scope :por_empresa, ->(user_id) { where(IdEmpresa: user_id) } # model
  scope :activos, -> { where(Status: true) }
  scope :inactivos, -> { where(Status: false) }
end

app/controllers/incidencias_controller.rb
class IncidenciasController < ApplicationController
  before_action :set_incidencia, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!
  before_action :clear_search_index, :only => [:index]
  before_action :permiso_listar, only: [:index]
  before_action :permiso_create, only: [:create]
  before_action :permiso_update, only: [:update]
  before_action :permiso_destroy, only: [:destroy]

  def modulo
    @Descripcion_Modulo = "Catálogo de incidencias"
  end

  # GET /incidencias
  # GET /incidencias.json
  def index
    @search = Incidencia.activos.search(search_params)
    # make name the default sort column
    @search.sorts = 'Clave' if @search.sorts.empty?
    @incidencias = @search.result().page(params[:page])
    @incidencia = Incidencia.new
    @cantidad_incidencias_activos = Incidencia.activos.count

    respond_to do |format|
      format.html
      format.js #para que se puedan enviar los datos de la busqueda del @search de la gema
      format.csv { send_data @incidencias.to_csv}
      format.xls
    end
  end

  def inactivos

    @search = Incidencia.inactivos.search(search_params)
    # make name the default sort column
    @search.sorts = 'Clave' if @search.sorts.empty?
    @incidencias = @search.result().page(params[:page])
    @cantidad_incidencias_inactivos = Incidencia.inactivos.count

    respond_to do |format|
      format.html
      format.js #para que se puedan enviar los datos de la busqueda del @search de la gema
      format.csv { send_data @incidencias.to_csv}
      format.xls
    end
  end

  def incidencia_check
    @incidenciax = Incidencia.find_by_Clave(params[:incidencia][:Clave])
    respond_to do |format|
    format.json { render :json => !@incidenciax }
    end
  end


  # GET /incidencias/1
  # GET /incidencias/1.json
  def show
  end

  # GET /incidencias/new
  def new
    @incidencia = Incidencia.new
  end

  # GET /incidencias/1/edit
  def edit
  end

  # POST /incidencias
  # POST /incidencias.json
  def create
    if @puede_crear != true
      return
    end
    @incidencia = Incidencia.new(incidencia_params)
    respond_to do |format|
      if @incidencia.save
        format.html { redirect_to @incidencia, notice: 'Incidencia was successfully created.' }
        format.json { render :show, status: :created, location: @incidencia }
        format.js {flash.now[:notice] = 'La incidencia se ha creado de forma exitosa.'} #ajax
      else
        format.html { render :new }
        format.json { render json: @incidencia.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al crear la incidencia.'} #ajax
      end
    end
  end

  # PATCH/PUT /incidencias/1
  # PATCH/PUT /incidencias/1.json
  def update
    if @puede_editar != true
      return
    end
    respond_to do |format|
      if @incidencia.update(incidencia_params)
        format.html { redirect_to @incidencia, notice: 'Incidencia was successfully updated.' }
        format.json { render :show, status: :ok, location: @incidencia }
        format.js {flash.now[:notice] = 'La incidencia se ha actualizado de forma exitosa.'} #ajax
      else
        format.html { render :edit }
        format.json { render json: @incidencia.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al actualizar la incidencia.'} #ajax
      end
    end
  end

  # DELETE /incidencias/1
  # DELETE /incidencias/1.json
  def destroy
    if @puede_destroy != true
      return
    end
    respond_to do |format|
      format.html { redirect_to incidencia_url, notice: 'incidencia was successfully destroyed.' }
      format.json { head :no_content }
      if @incidencia.Status == true
        @incidencia.update(Status:false)
        format.js {flash.now[:notice] = 'La incidencia se ha borrado de forma exitosa.'} #ajax
      else
        @incidencia.update(Status:true)
        format.js {flash.now[:notice] = 'La incidencia se ha habilitado de forma exitosa.'} #ajax
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incidencia
      @incidencia = Incidencia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incidencia_params
      params.require(:incidencia).permit(:Clave, :Descripcion, :Status, :IdEmpresa)
    end
end

app/helpers/incidencias_helper.rb
module IncidenciasHelper
end

app/views/incidencias/_form.html.erb
<%= form_for(@incidencia) do |f| %>
  <% if @incidencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incidencia.errors.count, "error") %> prohibited this incidencia from being saved:</h2>

      <ul>
      <% @incidencia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :CLAVE %><br>
    <%= f.text_field :CLAVE %>
  </div>
  <div class="field">
    <%= f.label :STATUS %><br>
    <%= f.text_field :STATUS %>
  </div>
  <div class="field">

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidencias/_incidencia.html.erb
<tr id="incidencia_<%= incidencia.id %>">
  <td class="col_left"><%= incidencia.try(:Clave)%></td>
  <td class="col_left"><%= incidencia.try(:Descripcion)%></td>
  <td class="col_left"><%= incidencia.try(:Status)%>
      <!--Modal - update producto-->
    <%= form_for(incidencia, :method => :put, remote: true, html: {class: "form-horizontal formulario-validado-update#{incidencia.id}"}) do |f| %><!--ajax-->
    <div nohidden class="modal fade si" id="myupdateincidencia_<%= incidencia.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Editar incidencia</h4>
          </div>

          <div class="modal-body">

              <div class="form-group">
                <%= f.label :Descripcion, "Descripcion:", class: "control-label col-md-3"  %>
                <div class="col-md-9">
                  <%= f.text_field :Descripcion, class: "form-control ", required: "true"   %>
                </div>
              </div>



              <div class="form-group">
                <%= f.label :Status,"Activo:", class: "control-label col-xs-7 col-sm-6 col-md-2"%>
                <div class="col-md-1">
                  <%= f.check_box :Status %>
                </div>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" id="myupdatebutton_<%= incidencia.id %>" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <%= submit_tag "Actualizar", class: "btn btn-primary", data: { disable_with: 'Actualizando' }%>
          </div>
        </div>
      </div>
    </div>
    <%end%>
      <script>
        $(".formulario-validado-update<%=incidencia.id%>").validate();

      </script>
  </td>


  <td>
  <div class="btn-group"><a class="btn dropdown-toggle btn-primary action-btn" href="#" data-toggle="dropdown">
   <%= t('basic.Acción') %>

   </a>
  <ul class="dropdown-menu posicion-menu">


    <li>

      <li>
        <button type="button" class="btn btn-default btn-lg btn-block" data-toggle="modal" data-target="#myupdateincidencia_<%= incidencia.id %>">
          Editar
        </button>
        <!--Destroy-->
        <% if incidencia.Status == true%>
        <%= link_to 'Eliminar', incidencia, method: :delete, class: "btn btn-default btn-xs", remote:true, data: {confirm: "¿Está seguro que desea eliminarlo?", disable_with: 'Eliminando...'}  %>
        <%else%>
          <%= link_to 'Habilitar', incidencia, method: :delete, class: "btn btn-default btn-xs", remote:true, data: {confirm: "¿Está seguro que desea habilitarlo?", disable_with: 'Habilitando...'} %>
        <%end%>
      </li>

    </li>



  </ul>
  </div>
  <!-- button group --></td>
</tr>

app/views/incidencias/_incidencias.html.erb
<%= search_form_for @search, :remote=>"true", url: incidencias_path, :method => :get do |f| %>
<div class="rwd">
  <table class="table table-striped table-bordered table-condensed table-hover rwd_auto">
        <thead>
          <tr>
            <th class="col_left"><%= sort_link @search, :Clave, "Clave","incidencia", {}, { :remote => true, :method => :get } %></th>
            <th class="col_left"><%= sort_link @search, :Descripcion, "Descripcion","incidencia", {}, { :remote => true, :method => :get } %></th>
            <th class="col_left"><%= sort_link @search, :Status, "Status","incidencia", {}, { :remote => true, :method => :get } %></th>
            <th class="action_col"><%= t("basic.action") %></th>
          </tr>
          <tr>
            <th><%= f.text_field :Clave_cont, class:"campo" %></th>
            <th><%= f.text_field :Descripcion_cont, class:"campo" %></th>
            <th><%= f.text_field :Status_cont, class:"campo" %></th>

            <th><%= f.submit "Buscar" %></th>
          </tr>

        </thead>
        <tbody>
        </tbody>
      </table>
  </div><% end %>




      <div class="rwd">
          <table class="table table-striped table-bordered table-condensed table-hover">
            <thead>
            <%= search_form_for @search, :remote=>"true", url: incidencias_path, :method => :get do |f| %>
              <tr>
                <th class="col_left"><%= sort_link @search, :Clave, "Clave","incidencia", {}, { :remote => true, :method => :get } %></th>
                <th class="col_left"><%= sort_link @search, :Descripcion, "Descripcion","incidencia", {}, { :remote => true, :method => :get } %></th>
                <th class="col_left"><%= sort_link @search, :Status, "Status","incidencia", {}, { :remote => true, :method => :get } %></th>
                <th class="action_col"><%= t("basic.action") %></th>
              </tr><% end %>
            </thead>
            <tbody id="container_incidencias">
              <%= render @incidencias %><!--carga todos los activos-->

            </tbody>
          </table>
          <%= paginate @incidencias %>

  </div>

app/views/incidencias/create.js.erb
<% if @puede_crear == true%>
  $("#mynewincidencia").modal('hide');
  $(".incidencia_clave").val('');
  $(".incidencia_descripcion").val('');

  $("#container_incidencias").prepend('<%= j render @incidencia %>'); //Prepend before append
  $("#incidencia_<%= @incidencia.id %>").hide().fadeIn(1000);
<%end%>
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/incidencias/destroy.js.erb
<% if @puede_destroy == true%>
  $("#incidencia_<%= @incidencia.id %>").fadeOut(500, function(){
    $(this).remove();
    $(".child").remove();
  });
<%end%>
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/incidencias/edit.html.erb
<h1>Editing Incidencia</h1>

<%= render 'form' %>

<%= link_to 'Show', @incidencia %> |
<%= link_to 'Back', incidencias_path %>

app/views/incidencias/inactivos.html.erb
<!--<p id="notice"><%= notice %></p>-->
<h1>Incidencias inactivas</h1>
<h3>Total: <%=@cantidad_incidencias_inactivos%></h3>
<style>
.container {
  width: 100%;
}

</style>

  <br>
  <br>

<div id="incidencias"><%= render 'incidencias' %></div>

<%= link_to 'Volver a Incidencias', incidencias_path, class: "btn btn-primary btn-lg" %>

app/views/incidencias/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<h1>Incidencias</h1>
<h3>Total: <%=@cantidad_incidencias_activos%></h3>
<style>
.container {
  width: 100%;
}

</style>
  <div class="row">
    <div class="text-center">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#mynewincidencia">
        Nueva incidencia
      </button>

    </div>
  </div>

  <br>
  <br>

<div id="incidencias"><%= render 'incidencias' %></div>



<!-- Modal create action -->
<%= form_for(@incidencia, remote: true, html: {class: "form-horizontal incidencia-validado"}) do |f| %> <!--ajax remote: true-->
  <div class="modal fade" id="mynewincidencia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Agregar incidencia</h4>
        </div>
        <div class="modal-body">


          <div class="form-group">

            <%= f.label :Clave, "Clave:", class: "control-label col-md-3"  %>
            <div class="col-md-7">
              <%= f.text_field :Clave, class: "form-control incidencia_clave clave_sin_espacios_y_sin_caracteres_especiales",autofocus: true, required: "true"   %>
            </div>

          </div>

          <div class="form-group">
            <%= f.label :Descripcion, "Descripcion:", class: "control-label col-md-3"  %>
            <div class="col-md-9">
              <%= f.text_field :Descripcion, class: "form-control incidencia_descripcion", required: "true"   %>
            </div>
          </div>



          <div class="form-group">
            <%= f.label :Status,"Activo:", class: "control-label col-xs-7 col-sm-6 col-md-2"%>
            <div class="col-md-1">
              <%= f.check_box :Status,{checked: true} %>
            </div>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewincidencia">Cerrar</button>
          <%= f.submit "Crear", class: "btn btn-primary", data: { disable_with: 'Creando' }%>
        </div>
      </div>
    </div>
  </div>
<%end%>
<%= link_to 'Incidencias eliminadas ó inhabilitadas<i class="fa fa-times-circle" aria-hidden="true"></i>'.html_safe, incidencias_inactivos_path, class: "btn btn-danger btn-xs"%>

app/views/incidencias/index.js.erb
$('#incidencias').html('<%= escape_javascript(render("incidencias")) %>');

app/views/incidencias/new.html.erb
<h1>New Incidencia</h1>

<%= render 'form' %>

<%= link_to 'Back', incidencias_path %>

app/views/incidencias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clave:</strong>
  <%= @incidencia.Clave %>
</p>

<p>
  <strong>Status:</strong>
  <%= @incidencia.Status %>
</p>

<p>
  <strong>Idempresa:</strong>
  <%= @incidencia.IdEmpresa %>
</p>

<%= link_to 'Edit', edit_incidencia_path(@incidencia) %> |
<%= link_to 'Back', incidencias_path %>

app/views/incidencias/update.js.erb
<% if @puede_editar == true %>
  $("#myupdateincidencia_<%= @incidencia.id %>").modal('hide');

  $("#incidencia_<%= @incidencia.id %>").fadeOut(500, function(){
    $(this).remove();
    $(".child").remove();
    $("#container_incidencias").prepend('<%= j render @incidencia %>');
  });
<%end%>
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);