config/routes.rb
    get 'incidencia_check', :on => :collection
  end
  get '/incidencias_inactivas', to: 'incidencias#inactivos', as: 'incidencias_inactivos'

  get 'mapa/index'

  resources :catmarcas do
    get 'catmarcas_check', :on => :collection
  end
  get '/marcas_inactivas', to: 'catmarcas#inactivos', as: 'catmarcas_inactivos'

  resources :catunidadmedida do
    get 'catunidadmed_check', :on => :collection
  end
  get '/medidas_inactivas', to: 'catunidadmedida#inactivos', as: 'catunidadmedida_inactivos'

  resources :catgrupos do
    get 'catgrupo_check', :on => :collection
  end
  get '/grupos_inactivos', to: 'catgrupos#inactivos', as: 'catgrupos_inactivos'

  resources :catbancos do
    get 'banco_check', :on => :collection
  end

  get '/bancos_inactivos', to: 'catbancos#inactivos', as: 'catbancos_inactivos'

  resources :cp

  get 'ventas/dashboard_ejecutivo_ventas', to: 'ventas#index', as: 'ventas1'
  get '/busqueda_clientes_captados', to: 'ventas#busqueda_clientes_captados', as: 'busqueda_clientes_captados'
  get '/busqueda_general_graficos', to: 'ventas#busqueda_general_graficos', as: 'busqueda_general_graficos'

  get 'ventas/dashboard_preventa', to: 'ventas#index2', as: 'ventas2'
  get '/busqueda_general_graficos_index2', to: 'ventas#busqueda_general_graficos_index2', as: 'busqueda_general_graficos_index2'
  get 'ventas/index3', as: 'ventas3'
  get 'ventas/index4', as: 'ventas4'

  resources :detallecob

  resources :stock do
    collection { post :import}#importar datos excel
  end

  resources :relactivos
  get '/activos_cliente/:id', to: 'relactivos#activos_cliente', as: 'activos_cliente'

  resources :activos do
     get 'activos_check_cb', :on => :collection
  end

  get '/activos_inactivos', to: 'activos#inactivos', as: 'activos_inactivos'

  resources :reldaycli
  get '/generar_ruta/:id/:id2', to: 'reldaycli#generar_ruta', as: 'generar_ruta'
  get '/busqueda_generacion_ruta', to: 'reldaycli#busqueda_generacion_ruta'

  get '/busqueda_vendedores_por_ruta', to: 'reldaycli#busqueda_vendedores_por_ruta'

  post '/reldaycli/datos', to: 'reldaycli#obtener_ruta_y_dia', as: 'ryd' #as es el nombre con el path que se le colocara
  get '/borrar_clientes_ruta_al_dia', to: 'reldaycli#borrar_clientes_ruta_al_dia', as: 'borrar_clientes_ruta_al_dia'

  get '/generar_ruta_agregar_de_forma_masiva', to: 'reldaycli#generar_ruta_agregar_de_forma_masiva', as: 'generar_ruta_agregar_de_forma_masiva'
  get '/generar_ruta_agregar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_agregar_seleccionar_todos_masivo', as: 'generar_ruta_agregar_seleccionar_todos_masivo'

  get '/generar_ruta_eliminar_de_forma_masiva', to: 'reldaycli#generar_ruta_eliminar_de_forma_masiva', as: 'generar_ruta_eliminar_de_forma_masiva'
  get '/generar_ruta_eliminar_seleccionar_todos_masivo', to: 'reldaycli#generar_ruta_eliminar_seleccionar_todos_masivo', as: 'generar_ruta_eliminar_seleccionar_todos_masivo'

  get '/asig_clientes_entre_vendedores', to: 'reldaycli#asig_clientes_entre_vendedores', as: 'asig_clientes_entre_vendedores'
  get '/proc_transf_cli_vend', to: 'reldaycli#proc_transf_cli_vend', as: 'proc_transf_cli_vend'

  resources :secrutas
  resources :relproclas
  resources :clasproductos
  resources :relcliclas
  resources :detallelpromaster
  get '/detallepromocion/:id', to: 'detallelpromaster#index', as: 'detallelpromasterid'
  resources :listapromomaster
  resources :clasclientes
  resources :listapromo do
    resources :detallepromo
    get 'promociones_check', :on => :collection
  end
  get '/promociones_inactivas', to: 'listapromo#inactivos', as: 'listapromo_inactivos'

  resources :room_categories
  resources :hotels
  resources :relruclas
  resources :clasrutas
  resources :continuidad
  resources :configrutasp

  resources :rutas do
    collection { post :import}#importar datos excel
    get 'rutas_check', :on => :collection
  end
  get '/rutas_inactivas', to: 'rutas#inactivos', as: 'rutas_inactivos'
  get '/datos_ruta', to: 'rutas#datos_ruta', as: 'datos_ruta'

  resources :relclirutas
  get '/ruta/:id/clientes', to: 'relclirutas#ruta_clientes', as: 'ruta_clientes'
  get '/borrar_clientes_ruta', to: 'relclirutas#borrar_clientes_ruta', as: 'borrar_clientes_ruta'

  get '/relcliruta_agregar_de_forma_masiva', to: 'relclirutas#relcliruta_agregar_de_forma_masiva', as: 'relcliruta_agregar_de_forma_masiva'
  get '/relcliruta_agregar_seleccionar_todos_masivo', to: 'relclirutas#relcliruta_agregar_seleccionar_todos_masivo', as: 'relcliruta_agregar_seleccionar_todos_masivo'
  get '/relcliruta_eliminar_de_forma_masiva', to: 'relclirutas#relcliruta_eliminar_de_forma_masiva', as: 'relcliruta_eliminar_de_forma_masiva'
  get '/relcliruta_eliminar_seleccionar_todos_masivo', to: 'relclirutas#relcliruta_eliminar_seleccionar_todos_masivo', as: 'relcliruta_eliminar_seleccionar_todos_masivo'

  resources :perfiles
  resources :mvodev do
    get 'mvodev_check', :on => :collection

  end
  get '/mvodevoluciones_inactivos', to: 'mvodev#inactivos', as: 'mvodev_inactivos'

  resources :encuestas
  get '/encuestas_inactivas', to: 'encuestas#inactivos', as: 'encuestas_inactivos'

  resources :relmens

  resources :mensajes do
    get 'mensajes_check', :on => :collection
  end
  get 'mensajes/_inactivos', to: 'mensajes#inactivos', as: 'mensajes_inactivos'

  resources :cuotas
  get '/cuotas_inactivos', to: 'cuotas#inactivos', as: 'cuotas_inactivos'

  resources :td_comision
  resources :detallelp
  resources :detallelp
  resources :listap do
    collection { post :import}#importar datos excel
  end
  resources :relclilis
  resources :detalleld
  resources :th_comision do
    collection { post :import}#importar datos excel
  end
  get '/th_comision_inactivos', to: 'th_comision#inactivos', as: 'th_comision_inactivos'
  resources :listad do
    collection { post :import}#importar datos excel
  end

  resources :mvomerma do
    get 'mvomerma_check', :on => :collection
  end
  get '/mvomerma_inactivos', to: 'mvomerma#inactivos', as: 'mvomerma_inactivos'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :motivosnoventa do
    get 'motivosnoventa_check', :on => :collection

  end
  get '/motivosnoventa_inactivos', to: 'motivosnoventa#inactivos', as: 'motivosnoventa_inactivos'
  get '/busqueda_noventas', to: 'reportesventas#busqueda_noventas', as: 'busqueda_noventas'

  resources :formaspag do
    get 'formaspag_check', :on => :collection
  end
  get '/formaspago_inactivos', to: 'formaspag#inactivos', as: 'formaspag_inactivos'

  resources :productosxpzas

  resources :productoenvase
  get '/Productos/:id/envase', to: 'productoenvase#index', as: 'producto_envase'

  resources :detalleld

  get '/listald/:id/productos', to: 'detalleld#index', as: 'producto_detalle'
  get '/listald/:id/clientes', to: 'relclilis#index', as: 'cliente_detalle'

  get '/listap/:id/productos', to: 'detallelp#index', as: 'productos_listap'

  get '/lp_productos_agregar_de_forma_masiva', to: 'detallelp#lp_productos_agregar_de_forma_masiva', as: 'lp_productos_agregar_de_forma_masiva'
  get '/lp_productos_agregar_seleccionar_todos_masivo', to: 'detallelp#lp_productos_agregar_seleccionar_todos_masivo', as: 'lp_productos_agregar_seleccionar_todos_masivo'
  get '/lp_productos_eliminar_de_forma_masiva', to: 'detallelp#lp_productos_eliminar_de_forma_masiva', as: 'lp_productos_eliminar_de_forma_masiva'
  get '/lp_productos_eliminar_seleccionar_todos_masivo', to: 'detallelp#lp_productos_eliminar_seleccionar_todos_masivo', as: 'lp_productos_eliminar_seleccionar_todos_masivo'

  get '/listap/:id/clientes', to: 'relclilis#indexlistap', as: 'cliente_listap'

  get '/rcl_clientes_agregar_de_forma_masiva', to: 'relclilis#rcl_clientes_agregar_de_forma_masiva', as: 'rcl_clientes_agregar_de_forma_masiva'
  get '/rcl_clientes_agregar_seleccionar_todos_masivo', to: 'relclilis#rcl_clientes_agregar_seleccionar_todos_masivo', as: 'rcl_clientes_agregar_seleccionar_todos_masivo'
  get '/rcl_clientes_eliminar_de_forma_masiva', to: 'relclilis#rcl_clientes_eliminar_de_forma_masiva', as: 'rcl_clientes_eliminar_de_forma_masiva'
  get '/rcl_clientes_eliminar_seleccionar_todos_masivo', to: 'relclilis#rcl_clientes_eliminar_seleccionar_todos_masivo', as: 'rcl_clientes_eliminar_seleccionar_todos_masivo'

  get '/Promociones/:id/clientes', to: 'relclilis#clientes_promociones', as: 'clientes_promociones'

  get '/comision/:id/detalle', to: 'td_comision#index', as: 'comision_detalle'

  post "/usuario_nuevo", to: 'usuarios#create', as:'usuario_nuevo'

  get '/Mensajes/:id/productos', to: 'relmens#index', as: 'mensaje_productos'
  get '/Mensajes/:id/clientes', to: 'relmens#clientes', as: 'mensaje_clientes'
  get '/Mensajes/:id/rutas', to: 'relmens#rutas', as: 'mensaje_rutas'

  devise_for :usuarios, controllers: {
    registrations: "usuarios/registrations",
    sessions: "usuarios/sessions",
    passwords: "usuarios/passwords"}
    resources :usuarios do
      get 'usuarios_check', :on => :collection
      get 'usuarios_check2', :on => :collection

    end
    devise_scope :usuario do
      get 'usuarios/sessions/busqueda_sucursales', as: 'busqueda_sucursales'#Actualiza el selectbox de la sucursal dependindo de la empresa en el login
    end

    get '/usuarios_inactivos', to: 'usuarios#inactivos', as: 'usuarios_inactivos'
    get '/usuario_sucursales', to: 'usuarios#usuario_sucursales', as: 'usuario_sucursales'
    get '/busqueda_usuario_perfil', to: 'usuarios#busqueda_usuario_perfil', as: 'busqueda_usuario_perfil'

  resources :productos do
    collection { post :import}#importar datos excel
    get 'productos_check', :on => :collection
    get 'productos_codbarras_check', :on => :collection
  end
  get '/datos_producto', to: 'productos#datos_producto', as: 'datos_producto'
  post 'create_producto_generico', to: 'productos#create_producto_generico', as: 'create_producto_generico'

  get '/productos_inactivos', to: 'productos#inactivos', as: 'productos_inactivos'

app/controllers/listapromomaster_controller.rb
class ListapromomasterController < ApplicationController
  before_action :set_listapromomast, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /listapromomaster
  # GET /listapromomaster.json
  def index
    @listapromomaster = Listapromomast.all
  end

  # GET /listapromomaster/1
  # GET /listapromomaster/1.json
  def show
  end

  # GET /listapromomaster/new
  def new
    @listapromomast = Listapromomast.new
  end

  # GET /listapromomaster/1/edit
  def edit
  end

  # POST /listapromomaster
  # POST /listapromomaster.json
  def create
    @listapromomast = Listapromomast.new(listapromomast_params)

    respond_to do |format|
      if @listapromomast.save
        format.html { redirect_to @listapromomast, notice: 'Listapromomast was successfully created.' }
        format.json { render :show, status: :created, location: @listapromomast }
        format.js {flash.now[:notice] = 'El grupo se ha creado de forma exitosa.'} #ajax
      else
        format.html { render :new }
        format.json { render json: @listapromomast.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al crear el grupo.'} #ajax
      end
    end
  end

  # PATCH/PUT /listapromomaster/1
  # PATCH/PUT /listapromomaster/1.json
  def update
    respond_to do |format|
      if @listapromomast.update(listapromomast_params)
        format.html { redirect_to @listapromomast, notice: 'Listapromomast was successfully updated.' }
        format.json { render :show, status: :ok, location: @listapromomast }
        format.js {flash.now[:notice] = 'El grupo se ha actualizado de forma exitosa.'} #ajax
      else
        format.html { render :edit }
        format.json { render json: @listapromomast.errors, status: :unprocessable_entity }
        format.js {flash.now[:alert] = 'Error al actualizar el grupo.'} #ajax
      end
    end
  end

  # DELETE /listapromomaster/1
  # DELETE /listapromomaster/1.json
  def destroy
    @grupoclientes = @listapromomast.relclilis.last
    @grupopromos = @listapromomast.detallelpromaster.last

    if (@grupoclientes == nil and @grupopromos == nil)
      @listapromomast.destroy
      respond_to do |format|
        format.html { redirect_to listapromomaster_url, notice: 'Listapromomast was successfully destroyed.' }
        format.json { head :no_content }
        format.js {flash.now[:notice] = 'El grupo se ha eliminado de forma exitosa.'} #ajax
      end
    else
      respond_to do |format|
        format.js {flash.now[:alert] = 'El grupo tiene registros.'} #ajax
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listapromomast
      @listapromomast = Listapromomast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listapromomast_params
      params.require(:listapromomast).permit(:Id, :ListaMaster, :Promociones, :IdEmpresa)
    end
end

app/helpers/listapromomaster_helper.rb
module ListapromomasterHelper
end

app/views/listapromomaster/_form.html.erb
<%= form_for(@listapromomast) do |f| %>
  <% if @listapromomast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listapromomast.errors.count, "error") %> prohibited this listapromomast from being saved:</h2>

      <ul>
      <% @listapromomast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Id %><br>
    <%= f.text_field :Id %>
  </div>
  <div class="field">
    <%= f.label :ListaMaster %><br>
    <%= f.text_field :ListaMaster %>
  </div>
  <div class="field">
    <%= f.label :Promociones %><br>
    <%= f.text_field :Promociones %>
  </div>
  <div class="field">
    <%= f.label :IdEmpresa %><br>
    <%= f.text_field :IdEmpresa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listapromomaster/_listapromomast.html.erb
<tr id="listapromomast_<%= listapromomast.id %>">
    <td><%= listapromomast.Id %></td>
    <td><%= listapromomast.ListaMaster %></td>
    <td>  <%= link_to '<i class="fa fa-gift" aria-hidden="true"></i> Promociones'.html_safe, detallelpromasterid_path(listapromomast), class:"btn btn-primary btn-xs boton", title:"Agregar promociones"   %>

      <%= link_to '<i class="fa fa-user-plus" aria-hidden="true"></i> Clientes'.html_safe, clientes_promociones_path(listapromomast), class:"btn btn-success btn-xs boton", title:"Agregar clientes"   %>
</td>

    <td>

        <!--Destroy-->
        <%= link_to '<i class="fa fa-times" aria-hidden="true"></i> Eliminar'.html_safe, listapromomast, method: :delete, class: "btn btn-danger btn-xs", remote:true, title:"Eliminar", data: {confirm: "¿Está seguro que desea eliminarlo?", disable_with: 'Eliminando...'}   %>


      </td>

</tr>

app/views/listapromomaster/create.js.erb
$(".listapromomast_nombre").val('');


$("#container_listapromomaster").prepend('<%= j render @listapromomast %>'); //Prepend before append
$("#listapromomast_<%= @listapromomast.id %>").hide().fadeIn(1000);
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/listapromomaster/destroy.js.erb
<% if (@grupoclientes == nil and @grupopromos == nil) %>
  $("#listapromomast_<%= @listapromomast.id %>").fadeOut(500, function(){
    $(this).remove();
    $(".child").remove();
  });
<%end%>
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);

app/views/listapromomaster/edit.html.erb
<h1>Editing Listapromomast</h1>

<%= render 'form' %>

<%= link_to 'Show', @listapromomast %> |
<%= link_to 'Back', listapromomaster_path %>

app/views/listapromomaster/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listapromomaster</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Listamaster</th>
      <th>Promociones</th>
      <th>Idempresa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listapromomaster.each do |listapromomast| %>
      <tr>
        <td><%= listapromomast.Id %></td>
        <td><%= listapromomast.ListaMaster %></td>
        <td><%= listapromomast.Promociones %></td>
        <td><%= listapromomast.IdEmpresa %></td>
        <td><%= link_to 'Show', listapromomast %></td>
        <td><%= link_to 'Edit', edit_listapromomast_path(listapromomast) %></td>
        <td><%= link_to 'Destroy', listapromomast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listapromomast', new_listapromomast_path %>

app/views/listapromomaster/new.html.erb
<h1>New Listapromomast</h1>

<%= render 'form' %>

<%= link_to 'Back', listapromomaster_path %>

app/views/listapromomaster/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @listapromomast.Id %>
</p>

<p>
  <strong>Listamaster:</strong>
  <%= @listapromomast.ListaMaster %>
</p>

<p>
  <strong>Promociones:</strong>
  <%= @listapromomast.Promociones %>
</p>

<p>
  <strong>Idempresa:</strong>
  <%= @listapromomast.IdEmpresa %>
</p>

<%= link_to 'Edit', edit_listapromomast_path(@listapromomast) %> |
<%= link_to 'Back', listapromomaster_path %>

app/views/listapromomaster/update.js.erb
$("#myupdatemensaje_<%= @mensaje.id %>").modal('hide');

$("#mensaje_<%= @mensaje.id %>").fadeOut(500, function(){
  $(this).remove();
  $(".child").remove();
  $("#container_mensajes").prepend('<%= j render @mensaje %>');

});
$("#notice").html("<%= escape_javascript(render :partial => 'partials/flash' , :locals => { :flash => flash }).html_safe %>");

setTimeout(function(){
  $('#notice').fadeIn("slow", function() {
    $(this).create();
  })
}, 1500);